name: ci

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1

      - name: Setup cache key and directory for gems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Rake CI command
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_DATABASE: rails_api_bootstrap_test
          POSTGRES_TEST_DATABASE: rails_api_bootstrap_test
          REDIS_HOST: redis
          RAILS_ENV: "test"
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
        run: |
          bundle exec rake ci

      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov/api.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
